version: "3.4"
services:
  api:
    build: .
    command: bin/rails s -b 0.0.0.0
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./:/app:delegated
    environment:
      DATABASE_URL: db
    networks:
      - backend
  gateway:
    build: .
    command: sh -c 'sleep 1 && npm start'
    ports:
      - 5000:5000
    depends_on:
      - api
    volumes:
      - ./:/app:delegated
    networks:
      - backend
    environment:
      USER_SERVICE_URL: http://api:3000/graphql/user_service
      ITEM_SERVICE_URL: http://api:3000/graphql/item_service
      ROLE_SERVICE_URL: http://api:3000/graphql/role_service
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: gql-poc
      POSTGRES_PASSWORD: federation

volumes:
  pgdata:

networks:
  backend:
