default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  user: graphql-poc
  password: federation
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  port: 5432

development:
  <<: *default
  database: graphql-poc-development

test:
  <<: *default
  database: graphql-poc-test

production:
  <<: *default
  database: graphql-poc-production
